[tool.poetry]
name = "docs requirements"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8"
sphinx = "*"
sphinx_material = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
