[tool.poetry]
name = "mypy requirements"
version = "0"
description = ""
authors = []

[tool.poetry.dependencies]
python = ">=3.8"
mypy = "*"
types-cachetools = "*"
types-requests = "*"
types-pyyaml = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
