name: Action Provider Tools CI
on:
  pull_request:
    branches:
      - master
  push:

jobs:
  ci:
    name: Run full action-provider-tools pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.x"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install the project and dependencies
        run: make install

      - name: Run linters
        run: make lint

      - name: Run tests
        run: make test
